### ISSUE TITLE
App Crash Report: Unhandled Error

### ISSUE THREAD

**Issue by stdavis** [agrc/api-client#267]
### What happened?

When I close the window and then click on the app in the dock, I get the following error message:
<img width="588" alt="image" src="https://github.com/agrc/api-client/assets/1326248/da064ed9-ebe1-444d-bded-e2763b906971">

This also happens with the app is automatically opened after restarting my machine.

This appears to be the same issue as #152

### Steps To Reproduce

1. Open app
2. Click on red "x" button to close the window (don't quit the app)
3. Click on the app icon in the dock to create a new window
4. The error message is displayed

1. Restart your machine with the app open
2. The error message is displayed when the app is reopened after the machine boots up

### App Version

1.7.4

### Electron Version

31.1.0

### Operating System

macOS Sonoma

#### Error message

`read ECONNRESET`

#### Stack trace

```st
Error: read ECONNRESET
    at AxiosError.from (file:///Applications/UGRC%20API%20Client.app/Contents/Resources/app.asar/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (file:///Applications/UGRC%20API%20Client.app/Contents/Resources/app.asar/node_modules/axios/lib/adapters/http.js:610:25)
    at RedirectableRequest.emit (node:events:519:28)
    at eventHandlers.<computed> (/Applications/UGRC API Client.app/Contents/Resources/app.asar/node_modules/follow-redirects/index.js:38:24)
    at ClientRequest.emit (node:events:519:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (file:///Applications/UGRC%20API%20Client.app/Contents/Resources/app.asar/node_modules/axios/lib/core/Axios.js:45:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by stdavis** [comment]
This does not seem to be an issue anymore.
