### ISSUE TITLE
App Crash Report

### ISSUE THREAD

**Issue by stdavis** [agrc/api-client#74]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### App Version

0.0.0-dev

### Electron Version

15.1.2

### Operating System

macOS Big Sur

#### Error message

`window.ugrc.aBadFunctionName is not a function`

#### Stack trace

```
TypeError: window.ugrc.aBadFunctionName is not a function
    at eval (webpack-internal:///./src/pages/Data.jsx:86:17)
    at invokePassiveEffectCreate (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3960:1047)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:657:119)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:677:45)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:696:126)
    at flushPassiveEffectsImpl (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3968:212)
    at unstable_runWithPriority (webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:465:16)
    at runWithPriority$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:2063:1059)
    at flushPassiveEffects (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3960:237)
    at eval (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3945:110)
```

**Comment by stdavis** [comment]
Please ignore, this is for demonstration purposes only.
